name: pixelmord
favicon: null
layout_spectrum: 0.6256750798784196
typography_spectrum: 0.8829241408966482
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.20731725776568055
  lightness: 0.9684433448128402
  saturation: 0.8420885370578617
  rhythmicContrast: 0.09128502197563648
purpose: []
